version: '3.4'

services:
  gruggbotbootstrapper:
    image: ${DOCKER_REGISTRY-}gruggbotbootstrapper
    container_name: gruggbot
    build:
      context: .
      dockerfile: Execute/GruggbotBootstrapper/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: "Development"
    volumes:
      - ./Settings/appsettings.json:/app/appsettings.json:ro

  seq:
    image: datalust/seq:latest
    container_name: gruggbot_seq
    ports:
      - 5341:5341
      - 80:80
    environment:
      ACCEPT_EULA: Y