version: '3.4'

services:
  gruggbotentry:
    container_name: gruggbot
    image: ${DOCKER_REGISTRY}gruggbotentry
    build:
      context: .
      dockerfile: Dockerfile
    image: gruggo/gruggbot:latest
